module.exports = {
	plugins: ['stylelint-order'],
	extends: ['stylelint-config-standard', 'stylelint-config-standard-scss'],
	rules: {
		'alpha-value-notation': 'number',
		'color-function-notation': 'legacy',
		'order/properties-order': [
			'display',
			'flex-flow',
			'justify-content',
			'align-items',
			'align-content',
			'gap',
			'row-gap',
			'column-gap',
			'position',
			'inset',
			'top',
			'left',
			'right',
			'bottom',
			'width',
			'height',
			'color',
			'padding',
			'padding-top',
			'padding-left',
			'padding-right',
			'padding-bottom',
		],
	},
};
